# Generated by Django 2.1.7 on 2019-03-25 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.TextField(max_length=80)),
                ('password', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=80)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticator.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing', models.CharField(max_length=80)),
                ('batch_no', models.CharField(max_length=80)),
                ('price', models.CharField(max_length=80)),
                ('expiry', models.CharField(max_length=80)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticator.Manufacturer')),
            ],
        ),
    ]
